### ISSUE TITLE
[GRIN-Wallet][Owner API] Calling wallet owner API "scan" method with invalid height

### ISSUE THREAD

**Issue by bladedoyle** [Grinnode-live/2020-grin-bug-bash-challenge#37] opened 2020-12-16 15:47 UTC
**Description**
Test a call to "scan()" through wallet owner api and pass an invalid "start_height".

**Prerequisites**

1. GRIN-Node
2. GRIN-Wallet

**Test procedure**

1. Run GRIN-Wallet in Owner API listener mode
2. Use [node.js](https://gist.github.com/marekyggdrasil/82716db323b34019bf02237012e0d16f) or [python](https://github.com/grinfans/grin.py/blob/main/wallet_v3.py) to run a encrypted request to [scan method](https://docs.rs/grin_wallet_api/4.0.0/grin_wallet_api/struct.Owner.html#method.scan) with an invalid graph heigh parameter such as `2004900`

**Expected result:**

Expect to reproduce an error for input block range.
Actual Result: ```Unable to parse response for get_pmmr_indices: JSON decode error: invalid type: null, expected struct OutputListing```

Provide requests and response full payloads as well as wallet and node logs.

Include the output of command

```
grin-wallet -V
```

and your environment

```
uname -a
```

**Comment by mojitoo** [comment] 2020-12-26 09:09
* grin-wallet 4.0.0
* Darwin MacBook-Pro-de-Workstation.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### Run GRIN-Wallet in Owner API listener mode
```
grin-wallet -r "https://grinnode.live:3413" owner_api
20201226 09:34:53.847 ERROR grin_wallet_impls::node_clients::http - Error calling get_version: Request error: Cannot make request: error trying to connect: tcp connect error: Connection refused (os error 61)
20201226 09:34:53.847 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Client Callback Error: Error calling get_version: Request error: Cannot make request: error trying to connect: tcp connect error: Connection refused (os error 61)
Password: 
20201226 09:34:55.357 WARN grin_wallet_controller::controller - Starting HTTP Foreign API on Owner server at 127.0.0.1:3420.
20201226 09:34:55.357 WARN grin_wallet_controller::controller - Starting HTTP Owner API server at 127.0.0.1:3420.
20201226 09:34:55.357 WARN grin_wallet_controller::controller - HTTP Owner listener started.
```
### Run scan method (chain height =0 )     
Add the below to wallet_v3.py and run it
pp.pprint(wallet.scan())
```
python3 /Users/workstation/Downloads/wallet_v3.py 
```
in this first example, scan will start from chain height 0
### Wallet log
```
20201226 09:34:55.357 WARN grin_wallet_controller::controller - Starting HTTP Foreign API on Owner server at 127.0.0.1:3420.
20201226 09:34:55.357 WARN grin_wallet_controller::controller - Starting HTTP Owner API server at 127.0.0.1:3420.
20201226 09:34:55.357 WARN grin_wallet_controller::controller - HTTP Owner listener started.
20201226 09:35:04.247 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 0% complete
20201226 09:35:13.273 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 0% complete
20201226 09:35:21.873 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 2% complete
20201226 09:35:28.420 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 4% complete
20201226 09:35:37.561 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 8% complete
20201226 09:35:43.946 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 10% complete
20201226 09:35:51.294 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 13% complete
20201226 09:35:58.653 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 16% complete
20201226 09:36:06.917 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 18% complete
20201226 09:36:13.403 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 22% complete
20201226 09:36:20.005 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 26% complete
20201226 09:36:24.380 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 29% complete
20201226 09:36:29.731 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 32% complete
20201226 09:36:37.429 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 33% complete
20201226 09:36:45.634 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 33% complete
20201226 09:36:52.955 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 34% complete
20201226 09:37:00.759 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 35% complete
20201226 09:37:08.464 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 35% complete
20201226 09:37:12.859 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 36% complete
20201226 09:37:19.464 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 36% complete
20201226 09:37:23.968 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 37% complete
20201226 09:37:28.335 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 38% complete
20201226 09:37:33.794 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 38% complete
20201226 09:37:38.504 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 39% complete
20201226 09:37:43.299 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 40% complete
20201226 09:37:47.663 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 41% complete
20201226 09:37:51.976 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 42% complete
20201226 09:37:56.332 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 42% complete
20201226 09:38:00.671 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 43% complete
20201226 09:38:04.967 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 44% complete
20201226 09:38:16.271 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 44% complete
20201226 09:38:20.725 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 45% complete
20201226 09:38:25.199 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 45% complete
20201226 09:38:30.437 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 46% complete
20201226 09:38:36.503 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 47% complete
20201226 09:38:41.128 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 47% complete
20201226 09:38:45.845 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 48% complete
20201226 09:38:51.810 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 48% complete
20201226 09:38:56.205 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 49% complete
20201226 09:39:01.045 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 50% complete
20201226 09:39:05.383 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 50% complete
20201226 09:39:10.701 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 51% complete
20201226 09:39:15.349 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 51% complete
20201226 09:39:24.459 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 52% complete
20201226 09:39:28.807 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 52% complete
20201226 09:39:35.732 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 53% complete
20201226 09:39:40.171 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 53% complete
20201226 09:39:54.831 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 54% complete
20201226 09:39:59.898 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 54% complete
20201226 09:40:04.233 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 55% complete
20201226 09:40:08.622 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 55% complete
20201226 09:40:18.477 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 56% complete
20201226 09:40:22.823 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 56% complete
20201226 09:40:27.170 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 57% complete
20201226 09:40:31.545 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 57% complete
20201226 09:40:37.366 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 58% complete
20201226 09:40:41.849 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 58% complete
20201226 09:40:46.250 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 59% complete
20201226 09:40:50.811 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 59% complete
20201226 09:40:58.424 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 60% complete
20201226 09:41:11.619 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 60% complete
20201226 09:41:19.388 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 61% complete
20201226 09:41:25.450 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 61% complete
20201226 09:41:30.139 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 62% complete
20201226 09:41:36.403 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 62% complete
20201226 09:41:41.298 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 63% complete
20201226 09:41:46.338 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 63% complete
20201226 09:41:50.835 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 64% complete
20201226 09:41:56.802 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 64% complete
20201226 09:42:01.642 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 65% complete
20201226 09:42:07.623 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 65% complete
20201226 09:42:13.177 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 66% complete
20201226 09:42:18.022 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 66% complete
20201226 09:42:22.400 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 67% complete
20201226 09:42:29.452 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 68% complete
20201226 09:42:36.498 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 68% complete
20201226 09:42:41.422 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 68% complete
20201226 09:42:52.466 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 69% complete
20201226 09:42:57.378 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 69% complete
20201226 09:43:02.336 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 70% complete
20201226 09:43:07.034 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 70% complete
20201226 09:43:11.791 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 71% complete
20201226 09:43:16.451 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 71% complete
20201226 09:43:20.856 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 71% complete
20201226 09:43:25.704 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 72% complete
20201226 09:43:30.055 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 72% complete
20201226 09:43:36.078 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 72% complete
20201226 09:43:40.410 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 72% complete
20201226 09:43:44.784 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 73% complete
20201226 09:43:49.165 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 73% complete
20201226 09:43:53.467 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 73% complete
20201226 09:43:57.759 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 74% complete
20201226 09:44:02.151 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 74% complete
20201226 09:44:06.475 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 74% complete
20201226 09:44:10.772 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 74% complete
20201226 09:44:15.162 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 75% complete
20201226 09:44:19.501 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 75% complete
20201226 09:44:23.815 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 75% complete
20201226 09:44:28.174 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 76% complete
20201226 09:44:33.353 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 76% complete
20201226 09:44:38.326 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 76% complete
20201226 09:44:45.476 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 77% complete
20201226 09:44:52.408 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 77% complete
20201226 09:45:02.694 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 78% complete
20201226 09:45:07.400 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 78% complete
20201226 09:45:12.192 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 78% complete
20201226 09:45:16.549 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 79% complete
20201226 09:45:22.970 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 79% complete
20201226 09:45:27.744 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 79% complete
20201226 09:45:32.507 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 80% complete
20201226 09:45:38.083 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 80% complete
20201226 09:45:42.748 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 80% complete
20201226 09:45:47.098 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 81% complete
20201226 09:45:52.380 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 81% complete
20201226 09:45:56.736 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 81% complete
20201226 09:46:01.237 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 82% complete
20201226 09:46:06.263 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 82% complete
20201226 09:46:10.754 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 83% complete
20201226 09:46:16.046 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 83% complete
20201226 09:46:20.636 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 83% complete
20201226 09:46:26.883 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 84% complete
20201226 09:46:32.264 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 84% complete
20201226 09:46:37.968 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 85% complete
20201226 09:46:42.337 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 85% complete
20201226 09:46:46.601 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 85% complete
20201226 09:46:50.890 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 85% complete
20201226 09:46:58.598 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 86% complete
20201226 09:47:03.461 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 86% complete
20201226 09:47:07.938 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 86% complete
20201226 09:47:12.684 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 86% complete
20201226 09:47:17.408 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 87% complete
20201226 09:47:21.698 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 87% complete
20201226 09:47:26.049 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 87% complete
20201226 09:47:30.395 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 88% complete
20201226 09:47:36.480 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 88% complete
20201226 09:47:42.017 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 88% complete
20201226 09:47:47.516 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 09:47:51.876 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 09:47:58.385 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 09:48:03.445 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 09:48:07.735 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 90% complete
20201226 09:48:12.251 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 90% complete
20201226 09:48:17.595 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 90% complete
20201226 09:48:22.024 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 90% complete
20201226 09:48:27.599 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 90% complete
20201226 09:48:35.512 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 91% complete
20201226 09:48:40.784 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 91% complete
20201226 09:48:45.175 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 91% complete
20201226 09:48:51.346 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 91% complete
20201226 09:48:57.247 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 91% complete
20201226 09:49:01.653 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 92% complete
20201226 09:49:06.026 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 92% complete
20201226 09:49:11.341 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 92% complete
20201226 09:49:15.651 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 92% complete
20201226 09:49:20.937 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 92% complete
20201226 09:49:25.701 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 93% complete
20201226 09:49:30.019 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 93% complete
20201226 09:49:36.579 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 93% complete
20201226 09:49:41.404 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 93% complete
20201226 09:49:45.719 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 93% complete
20201226 09:49:51.677 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 09:49:56.590 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 09:50:00.935 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 09:50:06.420 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 09:50:11.134 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 09:50:15.422 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 95% complete
20201226 09:50:21.477 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 95% complete
20201226 09:50:25.793 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 95% complete
20201226 09:50:30.308 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 95% complete
20201226 09:50:36.377 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 96% complete
20201226 09:50:40.715 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 96% complete
20201226 09:50:45.046 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 96% complete
20201226 09:50:49.383 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 96% complete
20201226 09:50:53.706 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 96% complete
20201226 09:50:58.189 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 97% complete
20201226 09:51:02.635 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 97% complete
20201226 09:51:07.061 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 97% complete
20201226 09:51:11.363 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 98% complete
20201226 09:51:16.015 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 98% complete
20201226 09:51:20.348 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 98% complete
20201226 09:51:25.098 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 98% complete
20201226 09:51:29.477 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:35.559 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:40.289 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:44.753 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:49.038 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:53.397 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:53.411 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:57.723 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:57.776 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:57.782 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:57.790 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:51:57.796 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:52:02.434 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:52:06.778 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:52:10.742 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:52:10.787 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 09:52:10.788 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning Complete
```

### Scan Method output
```
TRUE
```
Scanning Complete successfully

### Run scan method with valid height(chain height =1000000 ) 
```
20201226 10:04:41.159 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 0% complete
20201226 10:04:46.479 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 26% complete
20201226 10:04:50.815 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 45% complete
20201226 10:04:55.143 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 57% complete
20201226 10:04:59.535 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 66% complete
20201226 10:05:04.102 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 79% complete
20201226 10:05:04.119 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 79% complete
20201226 10:05:08.522 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 10:05:08.577 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 10:05:08.583 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 89% complete
20201226 10:05:12.831 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 10:05:12.837 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 10:05:12.842 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 94% complete
20201226 10:05:17.599 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 97% complete
20201226 10:05:21.938 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 10:05:21.988 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 99% complete
20201226 10:05:21.989 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning Complete
```
Scanning Complete successfully starting chain height 1000000

### Run scan method with invalid height(chain height =2000000 )

Wallet log 
```
20201226 10:06:16.251 WARN grin_wallet_libwallet::api_impl::owner_updater - Scanning - 0% complete
20201226 10:06:17.204 ERROR grin_wallet_impls::node_clients::http - Response { result: Some(Object({"Err": String("NotFound")})), error: None, id: Number(1), jsonrpc: Some("2.0") }
20201226 10:06:17.204 ERROR grin_wallet_impls::node_clients::http - Unable to parse response for get_pmmr_indices: JSON decode error: invalid type: null, expected struct OutputListing
```
```
python3 /Users/workstation/Downloads/grin.py 
Traceback (most recent call last):
  File "/Users/workstation/Downloads/grin.py", line 459, in <module>
    pp.pprint(wallet.scan(2000000))
  File "/Users/workstation/Downloads/grin.py", line 184, in scan
    resp = self.post_encrypted('scan', params)
  File "/Users/workstation/Downloads/grin.py", line 93, in post_encrypted
    raise WalletError(method, params, response_json["error"]["code"], response_json["error"]["message"])
__main__.WalletError: Callng scan with params {'token': 'dc90c8e4f0f1414f427fc73697813b33d750d64a1339636c1f90d12751b73930', 'start_height': 2000000, 'delete_unconfirmed': False} failed with error code -32099 because: ClientCallback: Unable to parse response for get_pmmr_indices: JSON decode error: invalid type: null, expected struct OutputListing
```

Error : ClientCallback: Unable to parse response for get_pmmr_indices: JSON decode error: invalid type: null, expected struct OutputListing

**Comment by marekyggdrasil** [comment] 2020-12-27 13:42
Looks like the expected result is reproduced. Thanks! @bladedoyle feel free to leave some comments if you think of something. Closing.

**Closed by marekyggdrasil** 2020-12-27 13:42 UTC
Labels: Grin-Wallet, Test-Case
